EXCLUSIONS = [
    'advisory',
    'board',
    'emeritus',
    'founding', 
    'managing', 
    'steering', 
    'assistant', 
    'honorary', 
    'special issue', 
    'book review',
    'film review',
    'emeriti',
    'adviser',
    'compiler',
    'administrative',
    'copyeditor',
    'previous',
    'member', 
    'social media',
    'consultant',
    'trainee',
    'correspondent',
    'reviews',
    'committee'
]